name: pic_maker
description: "Simple way to edit pictures."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  collection: ^1.19.1
  file_picker: ^10.3.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/meme_templates/
    - assets/stickers/


  fonts:
    - family: Impact
      fonts:
        - asset:  fonts/impact.ttf
        - asset:  fonts/impacted.ttf
        - asset: fonts/unicode.impact.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
